apiVersion: v1
kind: Service
metadata:
  name: breaker
  namespace: breaker-dev
  labels:
    app: breaker
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: breaker
  ports:
    - name: http
      port: 80
      targetPort: 8080
